---

all:
  hosts:
    localhost:
      ansible_connection: local
  vars:
    iso_files:
      - url: https://download.fedoraproject.org/pub/fedora/linux/releases/40/Everything/x86_64/iso/Fedora-Everything-netinst-x86_64-40-1.14.iso
        dest: src/Fedora-Everything-netinst-x86_64-40-1.14.iso
        checksum: sha256:4d1c0a7dda6c1d21a1483acb6c7914193158921113f947c5a0519d26bcc548b2
